---
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: msec
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - msec:9100
    metric_relabel_configs:
      - action: labeldrop
        regex: ^exported_instance$
      - action: labeldrop
        regex: ^exported_job
