---
services:
  db:
    image:
      ${MYSQL_IMAGE:-mysql:8.1}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MARIADB_HOME: /etc/cnf/mariadb
      MYSQL_HOME: /etc/cnf/mysql
    command:
      --tls-version=${TLS_VERSION:-TLSv1.2,TLSv1.3}
    volumes:
      - db:/var/lib/mysql
      - ./example/initdb.d:/docker-entrypoint-initdb.d
      - ./example/data:/mnt
      - ./example/cnf:/etc/cnf
      - ./example/my.cnf:/root/.my.cnf
    ports:
      - 3306:3306
  msec:
    image:
      ${MSEC_IMAGE:-ghcr.io/shortishly/msec:latest}
    environment:
      MSEC_REPLICA_UUID: ff275651-e77b-4acf-92f5-fb78b43ab40e
      MSEC_DATABASE_URI: mysql://root:secret@db:3306/shortishly
      MSEC_TIMEOUT_EXPIRY: 60000
    volumes:
      - cache:/data
    ports:
      - 6379:6379
      - 9100:9100
    links:
      - db
    pull_policy:
      ${PULL_POLICY:-always}
  prometheus:
    image:
      prom/prometheus:${PROMETHEUS_VERSION:-v2.47.2}
    ports:
      - 9090:9090
    configs:
      - source: prometheus_yml
        target: /etc/prometheus/prometheus.yml
    pull_policy:
      ${PULL_POLICY:-missing}
  grafana:
    image:
      grafana/grafana:${GRAFANA_VERSION:-10.1.5}
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/dashboards/home.json
      GF_LIVE_ALLOWED_ORIGINS: "https://*.preview.app.github.dev"
    volumes:
      - type: bind
        source: example/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: example/grafana/dashboards
        target: /etc/dashboards
      - grafana:/var/lib/grafana
    pull_policy:
      ${PULL_POLICY:-missing}
configs:
  prometheus_yml:
    file: example/prometheus.yml
volumes:
  db:
    driver: local
  grafana:
    driver: local
  cache:
    driver: local
